# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wizarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      wizarr:
        type: deployment
        replicas: 1
        strategy: Recreate

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/wizarrrr/wizarr
              tag: v2025.11.3
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: DISABLE_BUILTIN_AUTH
                value: "false"
              - name: TZ
                value: "Europe/Paris"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3

    service:
      app:
        controller: wizarr
        ports:
          http:
            port: 5690
            protocol: TCP

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: wizarr.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: wizarr-tls
            hosts:
              - wizarr.erwanleboucher.dev

    persistence:
      data:
        type: hostPath
        hostPath: /opt/yams/config/wizarr
        globalMounts:
          - path: /data
