apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: device-plugins-operator
  namespace: intel-device-plugins
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: '0.34.1-helm.0'
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: intel

