---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      homepage:
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest@sha256:7dc099d5c6ec7fc945d858218565925b01ff8a60bcbfda990fc680a8b5cd0b6e
            env:
              - name: TZ
                value: "Europe/Paris"
              - name: HOMEPAGE_ALLOWED_HOSTS
                value: "*"
            # Inject secrets as Environment Variables
            envFrom:
              - secretRef:
                  name: homepage-secrets
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: dash.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: homepage-tls
            hosts:
              - dash.erwanleboucher.dev
    # 2. ConfigMaps (The Application Configuration)
    configMaps:
      config:
        data:
          docker.yaml: ""
          kubernetes.yaml: ""
          bookmarks.yaml: |
            - Resources:
              - GitHub:
                  - icon: github.png
                    href: https://github.com/
              - Cloudflare:
                  - icon: cloudflare.png
                    href: https://dash.cloudflare.com/
              - n8n:
                  - icon: n8n.png
                    href: https://n8n.erwanleboucher.dev
                    description: Workflows
              - Profilarr:
                  - icon: wizard.png
                    href: https://profilarr.erwanleboucher.dev
                    description: Profile Manager
          settings.yaml: |
            title: Erwan's Home Lab
            background:
              image: https://images.unsplash.com/photo-1506318137071-a8bcbf6d9436?ixlib=rb-1.2.1&auto=format&fit=crop&w=2560&q=80
              opacity: 0.5
            layout:
              Media:
                style: row
                columns: 4
              Automation:
                style: row
                columns: 4
              System:
                style: row
                columns: 4
          widgets.yaml: |
            - resources:
                cpu: true
                memory: true
                disk: /
          services.yaml: |
            - Media:
              - Jellyfin:
                  icon: jellyfin.png
                  href: https://watch.erwanleboucher.dev
                  description: Media Player
                  widget:
                    type: jellyfin
                    url: http://jellyfin.media:8096
                    key: '{{ "{{" }}HOMEPAGE_VAR_JELLYFIN_KEY{{ "}}" }}'
              - Jellyseerr:
                  icon: jellyseerr.png
                  href: https://request.erwanleboucher.dev
                  description: Request Media
                  widget:
                    type: jellyseerr
                    url: http://jellyseerr.media:5055
                    key: '{{ "{{" }}HOMEPAGE_VAR_JELLYSEERR_KEY{{ "}}" }}'

            - Automation:
              - Home Assistant:
                  icon: home-assistant.png
                  href: https://home.erwanleboucher.dev
                  description: Home Automation
                  widget:
                    type: homeassistant
                    url: http://home-assistant.system:8123
                    key: '{{ "{{" }}HOMEPAGE_VAR_HASS_KEY{{ "}}" }}'
                    custom:
                      - state: sensor.h5075_9d45_temperature
                        label: bedroom temperature
                      - state: sensor.h5075_c14b_temperature
                        label: living room temperature
              - Sonarr:
                  icon: sonarr.png
                  href: https://sonarr.erwanleboucher.dev
                  description: TV Shows
                  widget:
                    type: sonarr
                    url: http://sonarr.media:8989
                    key: '{{ "{{" }}HOMEPAGE_VAR_SONARR_KEY{{ "}}" }}'
              - Radarr:
                  icon: radarr.png
                  href: https://radarr.erwanleboucher.dev
                  description: Movies
                  widget:
                    type: radarr
                    url: http://radarr.media:7878
                    key: '{{ "{{" }}HOMEPAGE_VAR_RADARR_KEY{{ "}}" }}'
              - Bazarr:
                  icon: bazarr.png
                  href: https://bazarr.erwanleboucher.dev
                  description: Subtitles
                  widget:
                    type: bazarr
                    url: http://bazarr.media:6767
                    key: '{{ "{{" }}HOMEPAGE_VAR_BAZARR_KEY{{ "}}" }}'
              - Prowlarr:
                  icon: prowlarr.png
                  href: https://prowlarr.erwanleboucher.dev
                  description: Indexer Manager
                  widget:
                    type: prowlarr
                    url: http://prowlarr.media:9696
                    key: '{{ "{{" }}HOMEPAGE_VAR_PROWLARR_KEY{{ "}}" }}'
              - qBittorrent:
                  icon: qbittorrent.png
                  href: https://qbit.erwanleboucher.dev
                  description: Downloader
                  widget:
                    type: qbittorrent
                    url: http://qbittorrent.downloads:8081
                    username: '{{ "{{" }}HOMEPAGE_VAR_QBIT_USER{{ "}}" }}'
                    password: '{{ "{{" }}HOMEPAGE_VAR_QBIT_PASS{{ "}}" }}'

            - System:
              - AdGuard Home:
                  icon: adguard-home.png
                  href: https://dns.erwanleboucher.dev
                  description: DNS Sinkhole
                  widget:
                    type: adguard
                    url: http://192.168.1.54:3000
              - Beszel:
                  icon: beszel.png
                  href: https://monitor.erwanleboucher.dev
                  description: Monitoring
                  widget:
                    type: beszel
                    url: http://beszel.monitoring:8090
                    username: '{{ "{{" }}HOMEPAGE_VAR_BESZEL_USER{{ "}}" }}'
                    password: '{{ "{{" }}HOMEPAGE_VAR_BESZEL_PASS{{ "}}" }}'
                    version: 2
              - Uptime Kuma:
                  icon: uptimekuma.png
                  href: https://monitor.erwanleboucher.dev
                  description: Monitoring
                  widget:
                    type: uptimekuma
                    url: http://uptime-kuma.monitoring
                    slug: default
    # 3. Mount the ConfigMaps as files
    persistence:
      config:
        type: configMap
        name: homepage-config
        advancedMounts:
          homepage:
            app:
              - path: /app/config/bookmarks.yaml
                subPath: bookmarks.yaml
              - path: /app/config/docker.yaml
                subPath: docker.yaml
              - path: /app/config/kubernetes.yaml
                subPath: kubernetes.yaml
              - path: /app/config/services.yaml
                subPath: services.yaml
              - path: /app/config/settings.yaml
                subPath: settings.yaml
              - path: /app/config/widgets.yaml
                subPath: widgets.yaml
