---
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: system
stringData:
  #ENC[AES256_GCM,data:GPkNWo7dmDkHX3jPgjlAKWbTfb/EyilffKiBuphZRIh78eZk+HKS35aa+uSyQb/Zo83XF+So1TOw6/WTT9KEUEhhixs=,iv:oTNm/0ROpmNxfw/+HUP0dESwro+e5pCqWrCdN4vY7nI=,tag:Zs4YCCzqeIJdVHdBbe9z4A==,type:comment]
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:tb+IawXvOZKDzFdjgFwtcaLi6bFA6tuALQjchdOHEoc=,iv:x/sUoinMJAc9fER6joIpffdvLdqdGmhsJRwtK+oCEgo=,tag:BOUicKF2sa3bAdOHrn0R6A==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:enl+1DjYb+8TFylQJNt+GslIVc53J15oPfMRgxySastmg6SBd+rTELpWyWVYv0Ra3g8VzFBKHmpzwBRTc3/Ho3EamhA=,iv:vBE/VKHVcHmjJ7bDPrqECx+pwWXwrPaGsGE4GWPHiik=,tag:0X9gCWz7lnR3l0oshyu6ag==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:BP6Vcb368UopWDNqQpb1cVN5aRr5eyQKNWNVO/Me5vD/po5y46oIQ82QbVOy+7IDFCCHxa4ZL8irJmpB+gLqREIop6XKsi+42iZ4gLXLUAZw+PG4IQcd2XuQ5K1A7HliCUW0AOL0UxlFZcbFmLhpGz1gIwY0NdmZUd5McXwrfbXp4jLI3r0mnF8VGl/b+3FCsUoqLaCc2J1GWeR2FPiPkK8u/rakWOvwPja23camxkBBr3b48BpA,iv:YxI3TY+h2OVwcaEg2r28LE3OmA/ian3cFCcy6twnZ3s=,tag:KZ7lF20sDbfRYzcckpyWjg==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:1cmRcd3AUXHGbzCitz2HhRD1PKozWi2tlV8P5EriIKk=,iv:+RjjclM5+HyLfXpjkPI3r+rY4c1Vb8GZuKuy9yDqNfg=,tag:78xhP1mY7c1evmyzSoujCA==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:ZQvqCEKhQd3sYA7uzmz//TsBmQYiOKZS+QnME2SZFEM=,iv:k1VmEPsPaJrSEaXa0VdVS9mcwZcm3etCCMyi03u90DU=,tag:6xMeTkYbAgTsrIhxw4p6NA==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:/dMo1h4IqXqGhkms4/va6w1mfrqRPM1ESX8XSZKfc2o=,iv:8fZfWgDILx4EyCh+pGcP01YKINTJSeVo4Qw8LqyBVrU=,tag:faaeBtRJW3s0Z0TNaaa1pA==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:JkXXiwzEldAquOZAerOZJ/7qp1zsG3iRhvuty+VvGJ0=,iv:naYPdPPliiilP5/TQadf+FKo/Agr4pU+b0wT+lde4tk=,tag:5A0QVWb0KbHoW/cEWUhx3Q==,type:str]
  HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:k/CpPtQ=,iv:fjJmCLsE221Srnx/iwo9S/zi6H6GVorxuEp1ZOjkNvk=,tag:/oFyfjJNq8EI5VGldNXj0g==,type:str]
  HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:1rOGK9T2d/BLu/4/zl/KloAe/7k=,iv:1Cybp8BDHaTRtSm4JqbRE4u6kq1ijKhLv67FXVF4fd4=,tag:ljIdtndziGr3AHnKVqF8rw==,type:str]
  HOMEPAGE_VAR_PORTAINER_KEY: ENC[AES256_GCM,data:FUkjrHKRgE2qbKu6eIR6anrJ5j/zmRFS83hO7b7Mx71HV4Iu33M5EIKZ5joItBvn,iv:4N0Cu5ex8CtCEaF34d87SRqawdntMUj+EGZwqMbAOVw=,tag:My/lBD/CDkpgX+m+/LBUhw==,type:str]
  HOMEPAGE_VAR_BESZEL_USER: ENC[AES256_GCM,data:R4ZnOmwc2j1ItFJkYKrWjyYH4q08pRJZ,iv:I1cvfm4GkuHtDzDASSTzo1vafM7j4vA3Omdu1wvUxbY=,tag:yf/SNiDDZcWP/e8GOxy5Rw==,type:str]
  HOMEPAGE_VAR_BESZEL_PASS: ENC[AES256_GCM,data:iS3TeY1paYV3FhFrsOEKsQ==,iv:pdU0S9LVlkgx/CncvHCUbPp+/E2sp5SEl2Co/rJuyl0=,tag:3NWcZBKPcXabeaAMwuxGxA==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd3Y3eGtEMUhoVDZ1UGN3
        K3MvMHB1MXBrT2lFVHdsYXd5V09UeGN6b0hjCjd0M3A5TEoyRVZPNjluWVkrZkZC
        TWE1MFJKcHhadzA0UmwwMGFZSDJ6aGMKLS0tIHZybys1TlZZTGdxUGo5Y2RWNzQ3
        UysyTWFybDM4S1BkSk1XeG9HTDRWLzgK2q6WhSmLPFDwcgsIPIyJcrJ8v174s/0d
        3KKC5IF9OZRiEhcJmiHSKO9wYmRglK2lZQoJif+VTU3YGtLSPzYQ5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T18:06:17Z"
  mac: ENC[AES256_GCM,data:Fc0EuzFxsxiK5XEFxm0faf/YyA+SFhZsSgTx8vFEY7CeDdgazI2nkP0+RAvlJi41EhFpJmDGDoDaThYNlqyB52tf82FTLf/byquovYyDEAi8Q3/9yFcbVxENoPYl3R0zmcqfbBP5XH7XcTGeyFpiSD2hXmHkPghbG4xYeLcT7X4=,iv:vY/R5uwYD6sgn8WCZsPhngJHDFHX33OTjPtEkmyWwk0=,tag:Nu366vJzPmCy3PAqahB7DA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
