# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: uptime-kuma
            patch: |
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "192.168.1.52"
                    hostnames:
                    - "dns.erwanleboucher.dev"
                    - "sonar.erwanleboucher.dev"
                    - "radarr.erwanleboucher.dev"
                    - "qbit.erwanleboucher.dev"
                    - "prowlarr.erwanleboucher.dev"
  values:
    controllers:
      uptimekuma:
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: "2.0.2"
              pullPolicy: Always

            probes:
                liveness:
                  enabled: true
                readiness:
                  enabled: true
                startup:
                  enabled: true
                  spec:
                    failureThreshold: 30
                    periodSeconds: 10
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: "k3s"
      tolerations:
        - key: "freebox"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    service:
        app:
          controller: uptimekuma
          ports:
            http:
              port: 3001

    ingress:
        app:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: "letsencrypt-production"
          hosts:
            - host: status.erwanleboucher.dev
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: app
                    port: http
          tls:
            - secretName: uptime-kuma-tls
              hosts:
                - status.erwanleboucher.dev

    persistence:
        data:
          type: persistentVolumeClaim
          existingClaim: config-nfs-pvc
          globalMounts:
            - path: /app/data
              subPath: uptime-kuma
