# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: uptime-kuma
            patch: |
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "192.168.1.52"
                    hostnames:
                    - "dns.erwanleboucher.dev"
                    - "sonar.erwanleboucher.dev"
                    - "radarr.erwanleboucher.dev"
                    - "qbit.erwanleboucher.dev"
                    - "prowlarr.erwanleboucher.dev"
  values:
    controllers:
      uptimekuma:
        type: deployment
        replicas: 1
        strategy: Recreate

        initContainers:
          migrate-data:
            image:
              repository: alpine
              tag: latest
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                echo "Checking for migration..."
                # If the new Longhorn volume is empty, copy data from the old HostPath
                if [ ! -f "/app/config/config.xml" ]; then
                  echo "Longhorn volume is empty. Migrating data..."
                  cp -av /host-config/. /app/config/
                  echo "Migration Complete!"
                else
                  echo "Volume has data. Skipping."
                fi
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: "2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba"
              pullPolicy: Always
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

    service:
      app:
        controller: uptimekuma
        ports:
          http:
            port: 3001
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: status.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: uptime-kuma-tls
            hosts:
              - status.erwanleboucher.dev
    persistence:
      host-config:
        type: persistentVolumeClaim

        existingClaim: uptime-kuma

        globalMounts:
          - path: /host-config
      config:
        type: persistentVolumeClaim
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        volumeName: uptime-kuma-config
        size: 2Gi
        globalMounts:
          - path: /app/data
