#!/bin/bash
# Script to split docker-services.yaml and docker-ingresses.yaml into individual folders

# Service to category mapping
declare -A SERVICE_CATEGORY
SERVICE_CATEGORY[jellyfin]="media"
SERVICE_CATEGORY[sonarr]="media"
SERVICE_CATEGORY[radarr]="media"
SERVICE_CATEGORY[prowlarr]="media"
SERVICE_CATEGORY[bazarr]="media"
SERVICE_CATEGORY[jellyseerr]="media"
SERVICE_CATEGORY[qbittorrent]="downloads"
SERVICE_CATEGORY[sabnzbd]="downloads"
SERVICE_CATEGORY[autobrr]="automation"
SERVICE_CATEGORY[profilarr]="automation"
SERVICE_CATEGORY[n8n]="automation"
SERVICE_CATEGORY[wizarr]="automation"
SERVICE_CATEGORY[portainer]="system"
SERVICE_CATEGORY[beszel]="system"
SERVICE_CATEGORY[open-webui]="system"

echo "This script will help you split services into individual folders."
echo "Run this when you're ready to reorganize your services."
echo ""
echo "Structure will be:"
echo "  apps/media/{jellyfin,sonarr,radarr,prowlarr,bazarr,jellyseerr}/"
echo "  apps/downloads/{qbittorrent,sabnzbd}/"
echo "  apps/automation/{autobrr,profilarr,n8n,wizarr}/"
echo "  apps/system/{portainer,beszel,open-webui}/"
echo ""
echo "Each service folder will contain:"
echo "  - service.yaml (Service + Endpoints)"
echo "  - ingress.yaml (Ingress with cert-manager annotation)"
echo "  - kustomization.yaml"
echo "  - README.md (migration guide)"
