# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      home-assistant:
        type: deployment
        replicas: 1
        strategy: Recreate
        initContainers:
          migrate-data:
            image:
              repository: alpine
              tag: latest
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                echo "Checking for migration..."
                # If the new Longhorn volume is empty, copy data from the old HostPath
                cp -av /host-config/. /config/
                echo "Migration Complete!"
        pod:
          # Use host network for device discovery
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.12.2@sha256:60dd3a329324b92017b7c8665648d65a9568a5a4205e93cad67ab9dec432f2d1
            env:
              - name: TZ
                value: "Europe/Paris"
            # Privileged for USB device access
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8123
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8123
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
            protocol: TCP
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: home.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: home-assistant-tls
            hosts:
              - home.erwanleboucher.dev
    persistence:
      host-config:
        type: persistentVolumeClaim
        existingClaim: home-assistant-config
        globalMounts:
          - path: /host-config
      config:
        type: persistentVolumeClaim
        storageClass: "local-path"
        volumeName: home-assistant-config-local
        accessMode: ReadWriteOnce
        size: 4Gi
        globalMounts:
          - path: /config
      # Mount /etc/localtime for timezone
      localtime:
        type: hostPath
        hostPath: /etc/localtime
        globalMounts:
          - path: /etc/localtime
            readOnly: true
      # Mount /run/dbus for system bus access
      dbus:
        type: hostPath
        hostPath: /run/dbus
        globalMounts:
          - path: /run/dbus
            readOnly: true
      # Mount USB device for Zigbee/Z-Wave
      usb:
        type: hostPath
        hostPath: /dev/ttyUSB0
        globalMounts:
          - path: /dev/ttyUSB0
