# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ai
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-mac
      tolerations:
        - key: "transient"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      ollama:
        type: deployment
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ollama/ollama
              tag: 0.13.1@sha256:8850b8b33936b9fb246e7b3e02849941f1151ea847e5fb15511f17de9589aea1
            env:
              - name: OLLAMA_KEEP_ALIVE
                value: "0"
    service:
      app:
        controller: ollama
        ports:
          http:
            port: 11434
            protocol: TCP
    persistence:
      config:
        type: hostPath
        hostPath: /opt/yams/config/ollama
        globalMounts:
          - path: /config
