# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wizarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      wizarr:
        type: deployment
        replicas: 1
        strategy: Recreate
        initContainers:
          migrate-data:
            image:
              repository: alpine
              tag: latest
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                echo "Checking for migration..."
                # If the new Longhorn volume is empty, copy data from the old HostPath
                echo "Longhorn volume is empty. Migrating data..."
                cp -av /host-config/. /config/
                echo "Migration Complete!"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/wizarrrr/wizarr
              tag: v2025.12.0@sha256:83fc0b50985d196226b7c28a27062a1c4e63124a5d6d2448710aee222637b79e
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: DISABLE_BUILTIN_AUTH
                value: "false"
              - name: TZ
                value: "Europe/Paris"
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      app:
        controller: wizarr
        ports:
          http:
            port: 5690
            protocol: TCP
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: wizarr.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: wizarr-tls
            hosts:
              - wizarr.erwanleboucher.dev
    persistence:
      host-config:
        type: persistentVolumeClaim
        existingClaim: wizarr
        globalMounts:
          - path: /host-data
      config:
        type: persistentVolumeClaim
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        volumeName: wizarr-config
        size: 2Gi
        globalMounts:
          - path: /data
