apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: beszel
      version: "0.9.1" # Check for latest
      sourceRef:
        kind: HelmRepository
        name: beszel
        namespace: monitoring
  values:
    image:
      repository: henrygd/beszel
      tag: latest

    # 1. Service Configuration
    service:
      main:
        ports:
          http:
            port: 8090

    # 2. Ingress (Your Dashboard)
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: monitor.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - secretName: beszel-tls
            hosts:
              - monitor.erwanleboucher.dev

    # 3. Persistence (Save history)
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/beszel
        globalMounts:
          - path: /beszel_data

    # 4. Environment Variables (User/Pass handled in UI on first launch)
    # but we can set defaults or keys here if needed.
    env:
      # Optional: Disable the "first user creation" if you want to automate it via secret
      # For now, UI setup is easiest.
      # DISCORD WEBHOOK for system alerts (CPU > 90%, Disk Full)
      # You can also set this in the UI later easily.
      - name: DISABLE_Password_AUTH
        value: "false"

    # 5. The Agent (Runs on every node)
    agent:
      enabled: true
      image:
        repository: henrygd/beszel-agent
        tag: latest
      # Critical for K3s/Linux monitoring
      securityContext:
        privileged: true
      # Mounts for accurate disk/network stats
      extraVolumeMounts:
        - name: root-fs
          mountPath: /rootfs
          readOnly: true
      extraVolumes:
        - name: root-fs
          hostPath:
            path: /
