apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "8.4.3"
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: system
  values:
    rbac:
      enabled: true
    service:
      enabled: true
    envSecrets:
      dbEncryption:
        existingSecret: "db-encryption"
        key: "db-encryption-key"
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: homarr.erwanleboucher.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homarr-tls
          hosts:
            - homarr.erwanleboucher.dev
    persistence:
      homarrDatabase:
        enabled: true
        storageClassName: "local-path"
        size: "1Gi"
