---
# Standard agent for ARM k3s node
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-agent-standard
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      agent:
        type: daemonset
        pod:
          hostNetwork: true
        containers:
          app:
            image:
              repository: henrygd/beszel-agent
              tag: latest@sha256:730ac49d1a89d315b5a9424ad8cca2f586e981da7caf151c5ec2d599f474efad
            env:
              - name: LISTEN
                value: "45876"
              - name: KEY
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-api-key
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-hub-token
              - name: HUB_URL
                value: "http://beszel:8090"
              # Memory calculation method (htop for more accurate reporting)
              - name: MEM_CALC
                value: "htop"
              # Monitor Docker containers via socket
              - name: DOCKER_HOST
                value: "unix:///var/run/docker.sock"
              # Network interfaces - blacklist virtual/container interfaces
              - name: NICS
                value: "-veth*,docker*,br-*,flannel*,cni*,kube*,dummy*"
              # Sensors - monitor all available temperature sensors
              # Uncomment to filter specific sensors
              # - name: SENSORS
              #   value: "coretemp,k10temp"
              # Additional filesystems/disks to monitor beyond root
              # Uncomment and adjust if you have additional disks to monitor
              # - name: EXTRA_FILESYSTEMS
              #   value: "sdb,sdc1,nvme0n1"
            securityContext:
              privileged: true
              capabilities:
                add:
                  - CAP_PERFMON
                  - SYS_RAWIO
                  - SYS_ADMIN

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
        - key: "freebox"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "transient"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    service:
      app:
        controller: agent
        ports:
          http:
            port: 45876

    persistence:
      # Mount root filesystem to read disk usage
      rootfs:
        type: hostPath
        hostPath: /
        globalMounts:
          - path: /rootfs
            readOnly: true
      # Mount Docker socket for container monitoring
      docker-socket:
        type: hostPath
        hostPath: /var/run/docker.sock
        globalMounts:
          - path: /var/run/docker.sock
            readOnly: true
      # Mount /dev for SMART disk monitoring
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev

---
# Intel GPU-enabled agent for AMD64 home node
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-agent-intel
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      agent:
        type: daemonset
        pod:
          hostNetwork: true
        containers:
          app:
            image:
              repository: henrygd/beszel-agent-intel
              tag: latest@sha256:ed944888731daae9d12c9daaac270745832f13a7eb1ac17b77215a5415190b35
            env:
              - name: LISTEN
                value: "45876"
              - name: KEY
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-api-key
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-hub-token
              - name: HUB_URL
                value: "http://beszel:8090"
              # Memory calculation method (htop for more accurate reporting)
              - name: MEM_CALC
                value: "htop"
              # Monitor Docker containers via socket
              - name: DOCKER_HOST
                value: "unix:///var/run/docker.sock"
              # Network interfaces - blacklist virtual/container interfaces
              - name: NICS
                value: "-veth*,docker*,br-*,flannel*,cni*,kube*,dummy*"
            securityContext:
              privileged: true
              capabilities:
                add:
                  - CAP_PERFMON
                  - SYS_RAWIO
                  - SYS_ADMIN

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: amd64


    service:
      app:
        controller: agent
        ports:
          http:
            port: 45876

    persistence:
      # Mount root filesystem to read disk usage
      rootfs:
        type: hostPath
        hostPath: /
        globalMounts:
          - path: /rootfs
            readOnly: true
      # Mount GPU device for Intel GPU monitoring
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
      # Mount Docker socket for container monitoring
      docker-socket:
        type: hostPath
        hostPath: /var/run/docker.sock
        globalMounts:
          - path: /var/run/docker.sock
            readOnly: true
      # Mount /dev for SMART disk monitoring
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev
