apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent-secret
    namespace: monitoring
type: Opaque
stringData:
    beszel-api-key: ENC[AES256_GCM,data:4YzVJDzC4ltab9D67FgAeEUPz5hUMJEjUbmnOsRskS9zTcyEbOLn43D78EUXjhQgr7bTcVzAcdohMRbLQiD4tbOdz/pdA4kdmknKzcTLBT0=,iv:zDhF4MYgvUcDxw4WZUHtORJvTEpFHSMOtcY1YmHyyo0=,tag:LVOBqMbraneuy/J8iUGnwg==,type:str]
    beszel-hub-token: ENC[AES256_GCM,data:qdJOePJWtEwbvP4LMRUs/zGUHnAOwTL114E9KfkhaEQTGZQX,iv:sRSZ03U+fNDd/spc/tpYBvwi0H0Aexi1cZln35gS9j0=,tag:aDgiuhVmNxtjxA3bm7SE5w==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUHd6RW83QWM4OVpFMFBE
            M3FrdFhkaHBGTG0xN2tFbm5Nd3FBSEZINkE4Ci9SS2lBc3oxay9hdURIeC9PY2c2
            RDJUc3J0YmVORDgrTGlvSDhmREVUbVkKLS0tIDVreWYyVG14ZUNFU1hlSWt5bytj
            NkxpNGJUZUVFaklvdE9HcEJPL2RZS00KCOkmVWunVRkvVZlfhJU7n6gx8QdXuzb1
            YHyHaNc9N4Dcr0WLZEVGaAbAmhpNA5DnZ50WOp1w3ejTmPXHy0ykdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T23:34:38Z"
    mac: ENC[AES256_GCM,data:1nVHzQIzF58BlZ+YftmENhS4e4+CF2M/WFried6DHBuJ2KVuwlUtuCboaHuajTXaDTktvQ0dvwPo3mLQe3npi/Y2HaHherzieO4epaXA7Yc66bzvmqrYdhHV7pFkQzBNa3X6kB05Dd+1kqhE0zGlm/52vGpqj2dqXC50LlPWSvs=,iv:ayfGEK7Nk3d4r7FZj6/y2CUFow7FujZx/iY4QWcU8/c=,tag:ynB+M2l3fr4oEDBprzvFYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
