apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent-secret
    namespace: monitoring
type: Opaque
stringData:
    beszel-api-key: ENC[AES256_GCM,data:4YzVJDzC4ltab9D67FgAeEUPz5hUMJEjUbmnOsRskS9zTcyEbOLn43D78EUXjhQgr7bTcVzAcdohMRbLQiD4tbOdz/pdA4kdmknKzcTLBT0=,iv:zDhF4MYgvUcDxw4WZUHtORJvTEpFHSMOtcY1YmHyyo0=,tag:LVOBqMbraneuy/J8iUGnwg==,type:str]
    beszel-hub-token: ENC[AES256_GCM,data:W7HTqXx4khyvg8wupbmp6feVwSPGC3SGa9eqQdBBm2A75t0x,iv:JSBrnkoXqT0QT5i4dIb6XsPQM8A4pfdXgrNflaVMW/0=,tag:PSLryGe/0ocB+LtkLGd7Uw==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUHd6RW83QWM4OVpFMFBE
            M3FrdFhkaHBGTG0xN2tFbm5Nd3FBSEZINkE4Ci9SS2lBc3oxay9hdURIeC9PY2c2
            RDJUc3J0YmVORDgrTGlvSDhmREVUbVkKLS0tIDVreWYyVG14ZUNFU1hlSWt5bytj
            NkxpNGJUZUVFaklvdE9HcEJPL2RZS00KCOkmVWunVRkvVZlfhJU7n6gx8QdXuzb1
            YHyHaNc9N4Dcr0WLZEVGaAbAmhpNA5DnZ50WOp1w3ejTmPXHy0ykdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T23:44:46Z"
    mac: ENC[AES256_GCM,data:4PT1WtSf0wEondCiLBBTzXcALvsNBaNlvIbHDpue5Um1muc9Sw0esM0cU+bxNmncknViRJ67PlVRsPd76ruG+teQy49UvbVaYurEPaP6dUB8bM82neqWFUlfMOjDcUGGRWjIMXdF9QAcSHlFjrhvRXb2CNFGIbaHIxg7so8b7QU=,iv:K7MNAnvfNRCnAD2VYsPDwqpR8oUyDx7DPoRxJc97nCs=,tag:f9kue9GlGJxxrNM15vUKZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
