# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      profilarr:
        type: deployment
        replicas: 1
        strategy: Recreate

        containers:
          app:
            image:
              repository: santiagosayshey/profilarr
              tag: beta
            env:
              - name: TZ
                value: "Europe/Paris"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 6868
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 6868
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3

    service:
      app:
        controller: profilarr
        ports:
          http:
            port: 6868
            protocol: TCP

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: profilarr.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: profilarr-tls
            hosts:
              - profilarr.erwanleboucher.dev

    persistence:
      config:
        type: hostPath
        hostPath: /opt/yams/config/profilarr
        globalMounts:
          - path: /config
