# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qui
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      qui:
        type: deployment
        replicas: 1
        strategy: Recreate

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/autobrr/qui
              tag: v1.9.0@sha256:eac5948b97646c00ee87017c80e46ba6ed981fc4dfff518f05c74f38193e5e93
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: TZ
                value: "Europe/Paris"
              - name: QUI__HOST
                value: "0.0.0.0"
              - name: QUI__BASE_URL
                value: "/"
              - name: QUI__PORT
                value: "8080"

            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3

    service:
      app:
        controller: qui
        ports:
          http:
            port: 8080
            protocol: TCP

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: qui.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: qui-tls
            hosts:
              - qui.erwanleboucher.dev

    persistence:
      config:
        type: hostPath
        hostPath: /opt/yams/config/qui
        globalMounts:
          - path: /config

