apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmk
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      checkmk:
        type: deployment
        replicas: 1
        strategy: Recreate

        pod:
          # CheckMK runs as user 1000 (cmk) by default
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: checkmk/check-mk-raw
              tag: 2.3.0-latest
            env:
              - name: CMK_SITE_ID
                value: "cmk"
              - name: TZ
                value: "Europe/Paris"
              # Initial password (check logs if not set correctly first time)
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 2Gi # Prevent it from eating all RAM

            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
              liveness:
                enabled: true
                spec:
                  initialDelaySeconds: 60
              readiness:
                enabled: true
                spec:
                  initialDelaySeconds: 60

    service:
      app:
        controller: checkmk
        ports:
          http:
            port: 5000

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: monitoring.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: monitoring-tls
            hosts:
              - monitoring.erwanleboucher.dev

    persistence:
      # Main Data (Sites)
      data:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/checkmk
        globalMounts:
          - path: /omd/sites

      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /opt/omd/sites/cmk/tmp
