---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    # Image configuration
    image:
      repository: lscr.io/linuxserver/jellyfin
      tag: 10.11.4ubu2404-ls10
      pullPolicy: IfNotPresent

    # Environment variables
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: docker
      TZ: Europe/Paris

    # Service configuration
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8096
            protocol: TCP

    # Ingress configuration
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: watch.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: watch-tls
            hosts:
              - watch.erwanleboucher.dev

    # Persistence configuration
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/jellyfin
        mountPath: /config

      media:
        enabled: true
        type: hostPath
        hostPath: /srv/media
        mountPath: /data

      transcode:
        enabled: true
        type: emptyDir
        mountPath: /transcode

    # Resources
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 4000m
        memory: 8Gi

    # Hardware acceleration - Intel GPU
    # Security context for HWA
    securityContext:
      capabilities:
        add:
          - "SYS_ADMIN"
        drop:
          - "ALL"
      privileged: false

    # Additional group for video access (992)
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      supplementalGroups:
        - 992  # video group for /dev/dri access

    # Mount /dev/dri for hardware transcoding
    extraVolumes:
      - name: hwa
        hostPath:
          path: /dev/dri

    extraVolumeMounts:
      - name: hwa
        mountPath: /dev/dri

    # Health checks
    probes:
      liveness:
        enabled: true
        spec:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      readiness:
        enabled: true
        spec:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
