---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    # Single replica
    replicaCount: 1

    # Use LinuxServer.io image for compatibility with existing config
    image:
      repository: lscr.io/linuxserver/jellyfin
      tag: 10.11.4ubu2404-ls10
      pullPolicy: IfNotPresent

    # Deployment strategy
    deploymentStrategy:
      type: Recreate

    # Service configuration
    service:
      type: ClusterIP
      port: 8096
      portName: http

    # Ingress configuration
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: watch.erwanleboucher.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: watch-tls
          hosts:
            - watch.erwanleboucher.dev

    # Resources
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 4000m
        memory: 8Gi

    # Jellyfin environment variables
    jellyfin:
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"

    # Pod security context for /dev/dri access
    podSecurityContext:
      fsGroup: 1000
      supplementalGroups:
        - 44    # video group
        - 992   # render group

    # Container security context for hardware acceleration
    securityContext:
      capabilities:
        add:
          - CHOWN
          - SETGID
          - SETUID

    # Use hostPath for persistence (not PVC)
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/jellyfin
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: true
        type: hostPath
        hostPath: /srv/media

    # Mount /dev/dri for hardware transcoding using volumes
    volumes:
      - name: dri
        hostPath:
          path: /dev/dri

    volumeMounts:
      - name: dri
        mountPath: /dev/dri

    # Health probes
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      tcpSocket:
        port: http

    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      tcpSocket:
        port: http
