---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-primary
  namespace: adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: "0.x.x" # Flux will grab the latest stable
      sourceRef:
        kind: HelmRepository
        name: gabe565
  values:
    # 1. Pin to N150
    nodeSelector:
      kubernetes.io/hostname: "home"
    securityContext:
      capabilities:
        add:
          - NET_BIND_SERVICE
          - NET_RAW
    # 2. Internal Services (ClusterIP only)
    # MetalLB handles the public IP separately
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 3000
      dns-tcp:
        enabled: true
        type: ClusterIP
        externalTrafficPolicy: ""
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
      dns-udp:
        enabled: true
        type: ClusterIP
        externalTrafficPolicy: ""
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
    # 3. Storage (HostPath on NVMe)
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 10Gi
      tls:
        enabled: true
        type: secret
        name: adguard-tls-secret
        mountPath: /opt/adguardhome/ssl
        readOnly: true
    config: |-
      rewrites:
        - 'domain': "*.erwanleboucher.dev"
          'answer': "192.168.1.52"
      tls:
        enabled: true
        server_name: dns.erwanleboucher.dev
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        allow_unencrypted_doh: false
        certificate_path: /opt/adguardhome/ssl/tls.crt
        private_key_path: /opt/adguardhome/ssl/tls.key
