---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-sync
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-sync
  template:
    metadata:
      labels:
        app: adguard-sync
    spec:
      containers:
        - name: sync
          image: ghcr.io/bakito/adguardhome-sync:v0.8.2@sha256:0d8411bfaae9e1e368b9a5ca8f3df28e8f0a335e9975003cc47892c22524ca15
          env:
            # Connect using internal ClusterIP DNS names
            - name: ORIGIN_URL
              value: "http://adguard-primary-adguard-home.adguard.svc.cluster.local"
            - name: REPLICA_URL
              value: "http://adguard-backup-adguard-home.adguard.svc.cluster.local"
            - name: CRON
              value: "*/5 * * * *" # Sync every 5 minutes
            - name: LOG_LEVEL
              value: "info"
