apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-tls
  namespace: uptime-kuma
spec:
  secretName: uptime-kuma-tls-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: status.erwanleboucher.dev
  dnsNames:
    - status.erwanleboucher.dev
