apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: "2.24.0" # Flux will grab the latest stable
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: uptime-kuma
            patch: |
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "192.168.1.52"
                    hostnames:
                    - "home.erwanleboucher.dev"
                    - "watch.erwanleboucher.dev"
                    - "sonarr.erwanleboucher.dev"
                    - "radarr.erwanleboucher.dev"
                    - "dns.erwanleboucher.dev"
  values:
    image:
      repository: louislam/uptime-kuma
      tag: "2.0.2"
      pullPolicy: Always

    nodeSelector:
      kubernetes.io/hostname: "k3s"

    tolerations:
      - key: "freebox"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

    service:
      type: ClusterIP
      port: 80
      targetPort: 3001

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: status.erwanleboucher.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: uptime-kuma-tls
          hosts:
            - status.erwanleboucher.dev

    # Mariadb configurations
    mariadb:
      enabled: true

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi

