---

services:
  ollama:
    image: ollama/ollama:0.13.5@sha256:2c9595c555fd70a28363489ac03bd5bf9e7c5bdf2890373c3a830ffd7252ce6d
    container_name: ollama
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_THREADS=2
      - OLLAMA_KEEP_ALIVE=0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    volumes:
      # Persistent storage for downloaded models
      - ${INSTALL_DIRECTORY}/config/ollama:/root/.ollama
    networks:
      yams_network:
        ipv4_address: 172.20.0.50 # Fixed IP for stability
