---

services:
  ollama:
    image: ollama/ollama:0.13.4@sha256:78b19735971f9a2855c98ca39a775a43fd3ebe104af0fe2155b5261c34deef31
    container_name: ollama
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_THREADS=2
      - OLLAMA_KEEP_ALIVE=0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    volumes:
      # Persistent storage for downloaded models
      - ${INSTALL_DIRECTORY}/config/ollama:/root/.ollama
    networks:
      yams_network:
        ipv4_address: 172.20.0.50 # Fixed IP for stability
