services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    networks:
      yams_network:
    ports:
      - 5432:5432
    volumes:
      - ${INSTALL_DIRECTORY}/config/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    networks:
      yams_network:
    depends_on:
      - postgres
    # ports:
    #   - 27017:27017
    volumes:
      - ${INSTALL_DIRECTORY}/config/ferretdb:/state
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/postgres?sslmode=disable
