---

services:
  # jellyfin is used to serve your media to the client devices
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.4ubu2404-ls10@sha256:234ea8d508b2cba26054d0dac9d4c0353435dce483e8b266947d473629774559
    container_name: jellyfin
    group_add:
      - '992'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/config/${MEDIA_SERVICE}:/config
    ports: # plex
      - 8096:8096 # plex
    networks:
      - yams_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`watch.erwanleboucher.dev`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  jellyseerr:
    image: seerr/seerr:develop@sha256:cebdcb3d23986bef88221717ed3352a595a05d4168409d69efa10f5fc5be19ff
    init: true
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    ports:
      - 5055:5055
    volumes:
      - ${INSTALL_DIRECTORY}/config/jellyseer:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      yams_network:
        ipv4_address: 172.20.0.25
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`request.erwanleboucher.dev`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=myresolver"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:v2025.11.3@sha256:5809c5da07883e3e572b279e41998a6ae93a17f978da899cfe803bc8d7b459fe
    ports:
      - 5690:5690
    volumes:
      - ${INSTALL_DIRECTORY}/config/wizarr:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DISABLE_BUILTIN_AUTH=false
      - TZ=${TZ}
      - GUNICORN_WORKERS=2
    restart: unless-stopped
    networks:
      - yams_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wizarr.rule=Host(`wizarr.erwanleboucher.dev`)"
      - "traefik.http.routers.wizarr.entrypoints=websecure"
      - "traefik.http.routers.wizarr.tls.certresolver=myresolver"
      - "traefik.http.services.wizarr.loadbalancer.server.port=5690"
