---
# Beszel Monitoring - Hardware and System Monitoring
# This provides detailed hardware monitoring that complements Grafana Cloud

services:
  beszel:
    image: 'henrygd/beszel:0.17@sha256:185142e6c91bd44c77fef6cd31784aee0f782eb1d7193c3ee34a9902a936621c'
    container_name: beszel
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.20.0.30
    volumes:
      - ${INSTALL_DIRECTORY}/config/beszel_data:/beszel_data
      - ${INSTALL_DIRECTORY}/config/beszel_socket:/beszel_socket
    ports:
      - "8090:8090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`monitor.erwanleboucher.dev`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls.certresolver=myresolver"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    image: henrygd/beszel-agent-intel:0.17@sha256:ed944888731daae9d12c9daaac270745832f13a7eb1ac17b77215a5415190b35
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    cap_add:
      - CAP_PERFMON
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${INSTALL_DIRECTORY}/config/beszel_agent_data:/var/lib/beszel-agent
      - /:/extra/filesystem:ro
      - ${INSTALL_DIRECTORY}/config/beszel_socket:/beszel_socket
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /srv/media/.beszel:/extra-filesystems/sda__Media:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: http://192.168.1.40:8090

  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2
    container_name: uptime-kuma
    restart: always
    networks:
      - yams_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INSTALL_DIRECTORY}/config/uptime-kuma:/app/data
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://localhost:3001"
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`status.erwanleboucher.dev`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
