---

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 853:853/tcp # dns over tls
      - 853:853/udp # dns over tls
      - 3000:3000/tcp # initial setup web interface
      - 443:443/tcp # dns over https
    networks:
      homelab:
        ipv4_address: 192.168.1.53
        ipv6_address: fd0f:ee:b0::53
    volumes:
      - ${INSTALL_DIRECTORY}/config/adguard/conf:/opt/adguardhome/conf # app configuration
      - ${INSTALL_DIRECTORY}/config/adguard/work:/opt/adguardhome/work # app working directory
      - ${INSTALL_DIRECTORY}/config/adguard/certs:/opt/adguardhome/certs:ro
    environment:
      - TZ=${TZ}
