# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cleanuparr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      cleanuparr:
        type: deployment
        replicas: 1
        strategy: Recreate
        initContainers:
          migrate-data:
            image:
              repository: alpine
              tag: latest
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                echo "Checking for migration..."
                # If the new Longhorn volume is empty, copy data from the old HostPath
                echo "Longhorn volume is empty. Migrating data..."
                cp -av /host-config/. /config/
                echo "Migration Complete!"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/cleanuparr/cleanuparr
              tag: latest@sha256:4d387adbb67b8c181a6a71e07a9093a250a3d7b6c70570a95077e45037f62738
            env:
              - name: PORT
                value: "11011"
              - name: BASE_PATH
                value: ""
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: UMASK
                value: "022"
              - name: TZ
                value: "Europe/Paris"
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 11011
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 11011
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      app:
        controller: cleanuparr
        ports:
          http:
            port: 11011
            protocol: TCP
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: cleanuparr.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: cleanuparr-tls
            hosts:
              - cleanuparr.erwanleboucher.dev
    persistence:
      host-config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: cleanuparr
        globalMounts:
          - path: /host-config
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        volumeName: cleanuparr-config
        size: 2Gi
        globalMounts:
          - path: /config
      downloads:
        type: hostPath
        hostPath: /srv/media
        globalMounts:
          - path: /downloads
