---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: "v0.18.3"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sig-node-feature-discovery
        namespace: kube-system
