# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/k8s-monitoring-helm/refs/heads/main/charts/k8s-monitoring/values.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.6.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    cluster:
      name: homelab
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-65-prod-eu-west-2.grafana.net./api/prom/push
        auth:
          type: basic
          usernameKey: "prom-username"
          passwordKey: "password"
        secret:
          create: false
          name: grafana-cloud-credentials
      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-012.grafana.net./loki/api/v1/push
        auth:
          type: basic
          usernameKey: "loki-username"
          passwordKey: "password"
        secret:
          create: false
          name: grafana-cloud-credentials
    clusterMetrics:
      enabled: true
    prometheusOperatorObjects:
      enabled: true
    clusterEvents:
      enabled: true
    podLogs:
      enabled: true
    alloy-metrics:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-cloud-credentials
                key: password
          - name: CLUSTER_NAME
            value: homelab
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-011.grafana.net
        auth:
          type: basic
          usernameKey: "fleet-username"
          passwordKey: "password"
        secret:
          create: false
          name: grafana-cloud-credentials
    alloy-singleton:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-cloud-credentials
                key: password
          - name: CLUSTER_NAME
            value: homelab
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-011.grafana.net
        auth:
          type: basic
          usernameKey: "fleet-username"
          passwordKey: "password"
        secret:
          create: false
          name: grafana-cloud-credentials
    alloy-logs:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-cloud-credentials
                key: password
          - name: CLUSTER_NAME
            value: homelab
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-011.grafana.net
        auth:
          type: basic
          usernameKey: "fleet-username"
          passwordKey: "password"
        secret:
          create: false
          name: grafana-cloud-credentials
