---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
type: Opaque
stringData:
  prom-username: ENC[AES256_GCM,data:BEChK+5Mbw==,iv:QAoQS5Ha66cnZThbWakiFCHPzTkyzDzisGT3ZrtahUU=,tag:MXs/sGArxsFjvlHQZULaMA==,type:str]
  loki-username: ENC[AES256_GCM,data:gMZo/YRcgA==,iv:nnxjC6WjuGl+yyb+G1lmRfEbtB4sPK6qxNJ6HWylHWE=,tag:2xj80C6i/YB4oBzZnhBngA==,type:str]
  fleet-username: ENC[AES256_GCM,data:yPzBM9XSxQ==,iv:xu14HKeX86loQqky/gh1Lb8/EE6E7sd2+glGlM4x4XQ=,tag:gsjM3Ajh7rhPaUmef00GgA==,type:str]
  password: ENC[AES256_GCM,data:QnwzMzxe20jTxPmZeTS01LBD0nT3pxhYpTjm9o2WnsnPVUirDvBtVNNt4xuHHUG0sV2QNgAFf5lIAEEtv/bXAW6Jf7xUKUMsorQQ3sFB8H54lMmnfd3b/jKZw9//4wSGnJ215XkyHztdqt7OwKaBkvEpdvntdsvcaAS0hGjvwcFbuQ5GwvX2yUgctyW+5XEx6a583nTpdoOaua45waOWaATXeBiT65Ot,iv:jxe18M8jPmqp+JmFyLm0Y8qtU7EDQmksbx1J4jVAqEI=,tag:VPU2Gjp+oFwVdAystEQVJQ==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDNlSGxxZ1hIczUrenJY
        UmEzR2FYZzJyK2xGeUoxL2ZVRkc1UXMvcXcwClpmT1RTbE5YM0FySFh3NEV0dHJV
        SGtoYnA0YTZrY0t6dFZ5UUs3OFk4Tk0KLS0tIDd1cVg0allmWlIxcDExNTRQNzFY
        UzRhOGlweGRvQUhBLzFDc3F5T1lZUHMKi8EHlMZwb/m2ZjabmcG0dfvwBwjhdmzY
        omfd0MgrEiOvh3mBG4hNKzwG5MJZD8MnzGKtr5IiKqXBgnR4UTASHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T19:38:59Z"
  mac: ENC[AES256_GCM,data:ZCxeAgsg91eYjiK1GFA4/v4zNnRyqUJxiw11DfMxBDIDQ60MjgGZaKkqBdp5EKm2tjkdw73TiBWorwnLsAea+G/7pkrX1kbh9b4uM2GczBE0dlyTq6OXIWsDSgR49CjeVOVzCOJnircvsOAdri6+DH+6M9e2rur7eqaaGQLRbjA=,iv:dHx/uYp6VJHg2h9Hs5aEdVRMqRqNzy/4wQ2wfd1NbS8=,tag:i5QGzOxxT5hlw13E7R839A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
