apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls
  namespace: adguard
spec:
  secretName: adguard-tls-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dns.erwanleboucher.dev
  dnsNames:
    - dns.erwanleboucher.dev
