apiVersion: v1
kind: Service
metadata:
  name: adguard-ha-dns
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-vip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.53
  externalTrafficPolicy: Cluster # Allows routing to the other node if needed
  selector:
    app.kubernetes.io/name: adguard-home # Matches both Primary and Backup pods
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-tls
      port: 853
      protocol: TCP
      targetPort: 853
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-ha-web
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-web-vip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.54
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - name: http
      port: 3000
      targetPort: 80
