apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-backup
  namespace: adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: "0.3.25"
      sourceRef:
        kind: HelmRepository
        name: adguard-community
  values:
    # 1. Pin to the Freebox Node
    nodeSelector:
      kubernetes.io/hostname: "k3s"

    # 2. Persistence (Smaller disk for backup)
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 5Gi
      tls:
        enabled: true
        type: secret
        name: adguard-tls-secret
        mountPath: /opt/adguardhome/ssl
        readOnly: true

    # 3. Networking
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 80
      dns-tcp:
        enabled: true
        type: ClusterIP
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
      dns-udp:
        enabled: true
        type: ClusterIP
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP

    # 4. Config (Same as primary)
    config: |
      tls:
        enabled: true
        server_name: dns.erwanleboucher.dev
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        allow_unencrypted_doh: false
        certificate_chain: /opt/adguardhome/ssl/tls.crt
        private_key: /opt/adguardhome/ssl/tls.key
