apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-primary
  namespace: adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: "0.x.x" # Flux will grab the latest stable
      sourceRef:
        kind: HelmRepository
        name: gabe565
  values:
    # 1. Pin to N150
    nodeSelector:
      kubernetes.io/hostname: "home"

    # 2. Internal Services (ClusterIP only)
    # MetalLB handles the public IP separately
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 80
      dns-tcp:
        enabled: true
        type: ClusterIP
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
      dns-udp:
        enabled: true
        type: ClusterIP
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP

    # 3. Storage (HostPath on NVMe)
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/adguard-primary/conf
        mountPath: /opt/adguardhome/conf
      work:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/adguard-primary/work
        mountPath: /opt/adguardhome/work
      # Mount the TLS cert
      tls:
        enabled: true
        type: secret
        name: adguard-tls-secret
        mountPath: /opt/adguardhome/ssl
        readOnly: true

    # 4. Configuration (AdGuardHome.yaml)
    config: |
      tls:
        enabled: true
        server_name: dns.erwanleboucher.dev
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        allow_unencrypted_doh: false
        certificate_chain: /opt/adguardhome/ssl/tls.crt
        private_key: /opt/adguardhome/ssl/tls.key
