apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-backup
  namespace: adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: gabe565
  values:
    # 1. Pin to Freebox
    nodeSelector:
      kubernetes.io/hostname: "k3s"

    # 2. Internal Services
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 80
      dns-tcp:
        enabled: true
        type: ClusterIP
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
      dns-udp:
        enabled: true
        type: ClusterIP
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP

    # 3. Storage (HostPath on Freebox VM Disk)
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /mnt/data/adguard/conf # Adjust this path for your VM
        mountPath: /opt/adguardhome/conf
      work:
        enabled: true
        type: hostPath
        hostPath: /mnt/data/adguard/work # Adjust this path for your VM
        mountPath: /opt/adguardhome/work
      tls:
        enabled: true
        type: secret
        name: adguard-tls-secret
        mountPath: /opt/adguardhome/ssl
        readOnly: true

    # 4. Config (Same as primary)
    config: |
      tls:
        enabled: true
        server_name: dns.erwanleboucher.dev
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        allow_unencrypted_doh: false
        certificate_chain: /opt/adguardhome/ssl/tls.crt
        private_key: /opt/adguardhome/ssl/tls.key
