# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      jellyseerr:
        type: deployment
        replicas: 1
        strategy: Recreate
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: seerr/seerr
              tag: develop@sha256:e3287fcaaafc898f3844899bd91cdc08771a5f4b231eb2cfa1c4dcc4f4f06f22
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: LOG_LEVEL
                value: "debug"
              - name: TZ
                value: "Europe/Paris"
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 1Gi
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  initialDelaySeconds: 20
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 30
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 5055
            protocol: TCP
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: request.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: request-tls
            hosts:
              - request.erwanleboucher.dev
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /app/config
