apiVersion: v1
kind: Secret
metadata:
    name: vpn-config
    namespace: downloads
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:B+9HGsbpxQfA,iv:srUHO3xdf/oxdDmHgNhaIn3+iQ8EhG4kW8OKjXKAj/w=,tag:xLs2GRpHuakEF/J9vhnrnw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:dc06Qd4Jo3Wl,iv:/k7UZVJ5Vb4J71rvTOHj5kT5nxJ1ml5+owu7Hl9bTsU=,tag:WUakIZyKM7G89W0UAAJ7zw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:d1El/WCTFJjr01kHKxlo156ghBXad57hsSmqtuemFD+/SlRxvgs5pLHKOZg=,iv:L2srZhJMVpVBTuHlO6MYfnOzakOIIpMWEqOJhjyYhfo=,tag:Fjr+D2sxXKuK/y2jQjrTNw==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:J1E=,iv:Nk5t8h5OY+KO3xBMQyVWMYAthQeoL8G4j96pK1HmgP0=,tag:6Q+X02Ft7kqRTVMWkmQBPA==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:fk4qcCI+cm+G,iv:/MTknlOUxuaaEMXk5nSa4NabLxRQamZ2+p1sb2+sNZo=,tag:sCah3V6epG7womzsZKpE3Q==,type:str]
    PORT_FORWARD_ONLY: ENC[AES256_GCM,data:3Q0=,iv:O09Sf9gXVOkedQVMlSpXN5yS8YrU6p9nWwl3is4eP2o=,tag:pWzjYQk2qzF008sK9sH9HA==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:LxHDAlb/p83F0Q==,iv:5kMbRK3cO+SaVoNLXExD/313+YlIxIwIWG1AlloPhDU=,tag:JK1cNnrIwP0+ycqs0lyarw==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:Uk5Ch7lluBqe0jw=,iv:yuVoLna047wp1Sdw4JNz0oLc4y48cYh9Y/rPS5khWWE=,tag:uT5+YzHvrbyYJto6fwKnNg==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SzB4TVN2dHpFTmtsY1ZE
            aElNZEdVYmRyQ2ZqVjliL3JxREpMcGJIeW1JCjJMb3laTWFSOWgxU2ZoNGJzcHRD
            cXR4RVlJcERvcERYcHpjeEQ2M1psQVUKLS0tIDhBSElHdStVSnRhS2Q2NGxsZmdt
            ZGhOM1FOb3B1am1vdHluUkxuMFVNcmMKV5Fd9Ee+IgQ8hJxF6Mq64boCMNFO3h5O
            3N3JPyTeYImPdMlUcXok3MTzobPR45nVSHoeXEKZfaDWzVMBD9VuPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T16:30:50Z"
    mac: ENC[AES256_GCM,data:2APuIG1CFbyTNvkMMbEA6qMIjID6nEihAF1/IbL5TRSZD/L9LM2yINtihKFSpDbzL77lzMZpd7a5LdwHiPehyq/qz2ZHJzvxOdXTkLeOPWOxKHDad9PD+HLgcWrJizj0AG7hNQFD27qr6+l6ZGXSLDIYtdzzV7z5VHaTaADj/8Q=,iv:krfw+wab7KBgrUT785K1G4Z4uMQAX0lkBZMoSDTehZk=,tag:KZe84UMcGlPHyC9fnxg8LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
