apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel-agent
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      agent:
        type: daemonset
        pod:
          hostNetwork: true
        containers:
          app:
            image:
              repository: henrygd/beszel-agent
              tag: latest
            env:
              - name: LISTEN
                value: "45876"
              - name: KEY
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-api-key
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: beszel-agent-secret
                    key: beszel-hub-token
              - name: HUB_URL
                value: "http://beszel:8090"
              # Memory calculation method (htop for more accurate reporting)
              - name: MEM_CALC
                value: "htop"
              # Monitor Docker containers via socket
              - name: DOCKER_HOST
                value: "unix:///var/run/docker.sock"
              # Network interfaces to monitor (all by default, use -prefix for blacklist)
              # - name: NICS
              #   value: "eth0,wlan*"
              # Sensors to monitor (all by default, use -prefix for blacklist)
              # - name: SENSORS
              #   value: "coretemp,k10temp"
              # Additional filesystems/disks to monitor
              # - name: EXTRA_FILESYSTEMS
              #   value: "sdb,sdc1"
              # Specify root filesystem device for accurate stats
              # - name: FILESYSTEM
              #   value: "/dev/sda1"
            securityContext:
              privileged: true
              capabilities:
                add:
                  - CAP_PERFMON
                  - SYS_RAWIO

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

    defaultPodOptions:
      tolerations:
      - key: "freebox"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

    service:
      app:
        controller: agent
        ports:
          http:
            port: 45876

    persistence:
      # Mount root filesystem to read disk usage
      rootfs:
        type: hostPath
        hostPath: /
        globalMounts:
          - path: /rootfs
            readOnly: true
      # Mount GPU device for hardware monitoring (Intel/AMD)
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
      # Mount Docker socket for container monitoring
      docker-socket:
        type: hostPath
        hostPath: /var/run/docker.sock
        globalMounts:
          - path: /var/run/docker.sock
            readOnly: true
