apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      beszel:
        type: daemonset
        replicas: 1
        strategy: Recreate

        containers:
          app:
            image:
              repository: henrygd/beszel
              tag: latest
            env:
              - name: TZ
                value: "Europe/Paris"
              # Port the application listens on internally
              - name: PORT
                value: "8090"

            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

    service:
      app:
        controller: beszel
        ports:
          http:
            port: 8090

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: monitor.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: beszel-tls
            hosts:
              - monitor.erwanleboucher.dev

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /opt/yams/config/beszel
        globalMounts:
          - path: /beszel_data
