apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent-secret
    namespace: monitoring
type: Opaque
stringData:
    beszel-api-key: ENC[AES256_GCM,data:ddJw6unzgo+qoS9q5ayKtqo+MxkreKRq6ItBGgtUFDLQ/Qc9gHmYzwKfi9RPhnPCVOX2JnotR0709tdYWIxCLmRpO2B6zfV0IZghVP+eA0I=,iv:zyUx6WHIWrZfnKwIWRu15jxcfUZBaWDhiAedjJb589s=,tag:mvcfEEUCqxb+lhn3vWbMNA==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVgzaUJObTBzUlVXejBS
            OUwrSy9BZE1FNElaa1g1L3VuU1BNTm1EZUI4Cmx4VzloNk5DWDV4OWloemxkNjFn
            NHZZZDhvN3VMMVF0bDFzMGNNaXdyYzQKLS0tIDN5YURFczBiZjlTdER0bWlmRkRq
            emU4L2xVNnJ4TlM5YTNzdEtJT2VnVk0KRxhwG9uZqDrCfg9dSP4TEoscH03FELEt
            LdPxljPCs95ikUsGh4HTIK+YiUZJPBdW1mLVILiWHnMb+eI9u0h1tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T15:50:56Z"
    mac: ENC[AES256_GCM,data:dPW97v/NisG537kMMAqrQ/6vsiw3UF6HJ2mMeeVTUUX3yME0b49V6OiIhvpsKtC31LTOX3mlNg1AsUpiGsDUWnadGnkrjCSL+YJtFx2B8SAnDNMHME90asnl5EW+0jVc5TQwVKJ2olkJFahaVxgSvE9DDZ2dHLOCOJcPwvEDnCM=,iv:YIf04VnRNoeIUUyvbIFNMGBx/rnt2R1upeHv1IBJqTM=,tag:nURrvnkgFDgvgj2R+YhLVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
