# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-sync
  namespace: backup
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          # Run at 5:00 AM every Sunday (After the local Longhorn backup finishes)
          schedule: "0 5 * * 0"
          concurrencyPolicy: Forbid

        pod:
          # Run on the node that physically holds the disk
          nodeSelector:
            kubernetes.io/hostname: "home"

        containers:
          app:
            image:
              repository: rclone/rclone
              tag: latest@sha256:0eb18825ac9732c21c11d654007170572bbd495352bb6dbb624f18e4f462c496
            env:
              # Point to the secret mounted below
              - name: RCLONE_CONFIG
                value: "/config/rclone.conf"
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                echo "🚀 Starting Offsite Sync to Google Drive..."

                rclone sync /data/backups/backupstore gdrive:longhorn-backups \
                  --transfers 32 \
                  --checkers 32 \
                  --fast-list \
                  --verbose \
                  --delete-during

                echo "✅ Offsite Sync Complete!"

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi

    persistence:
      config:
        type: secret
        name: google-drive-backup
        globalMounts:
          - path: /config
            readOnly: true

      source-data:
        type: hostPath
        hostPath: /srv/media
        globalMounts:
          - path: /data
            readOnly: true
