---
kind: Secret
apiVersion: v1
metadata:
  creationTimestamp: null
  name: google-drive-backup
  namespace: backup
stringData:
  rclone.conf: ENC[AES256_GCM,data:7xCGfeRlm3YLmJZm2NOMgo5Lrstu/fm1NcDjJR0TYdF7UZHk3ijcAivLVx8ZyS0V64NKV4FA3WC+eQl6sG9v8nHvmWAz4A7bMa/5hyX8sWVq+zkYJHevvXKBVSHOmQiHCIWCgbE65I4s5+A8S3I27rdPbmnsjCtSFPs7xNXlKp3UkWgNGzmvlyBhuqBKYAq1oeDtzOJ/N+kPIJRDDHoHbknBDCUC9OkbORD80pgN9kKkH+GwEL9U8cX1hiqScnROaSbVDFJWLr352JoAmIxAa5WwM/6gTKpNl71CtYAjeOnmj65n9gMWftS9GLMaXhN9G8+XtNO98m77442wEdIlrcGKueiY3OyYmTaQdgeqH3BNINfzPrGXUudxLWh5eASgFel/d1Avmh7E4O/EEE4ycGKjUcqXaSSwCxDBzvioI1L5D5b9uuL708zMndG3+5BKkwXdc1TKRgE+6lvjBLbJ6MHGKinFxmXpexqhDFxez4iEkGo6MK7EPRfYeMqrHKEU55MyBCJRtA5iRF1DDGTE1q22gQxewCrJ3j3SI8j+Uqzl/fmatgy8VAwC7ZqJSEf3r5mTrdHCer+3J0VexRZHHMkr40ztYdpPgpMZUMlD5KAA9ANE/poEtppvW8AGbtxTNVxnpPgeTkGGyEQux3aFJ5gsXDlrHR7c7lqv3mPhvMGAtbyu+OiZVqH7RHH1QeS4IxU2LRYKbLDdgHn+H/RWu1HcdJwBXBVfn4eFwvH4IfMYMFLSjOMI8EjubJrkHIEHPslV3yNvGlnOVxr2PmLV6J+tZ62tBOHYSuv3SmYOY8ujvt+ORbC+GvfnD85C07EI+Oxqn27HD+/iq9bs4U+ueZ6ELzLMwwyqnISp0txlvEn+0PI8tqiDx41ynqwn,iv:99dFsWuqm9v+f2PheHWcfaZykjEiMjsuToNwa+cNKck=,tag:tCxp4GY7GyGShjsNqrK2Ag==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aENnV2FaQyt2Yk5iSDRr
        d3RkSlFzaDF3TXJGZ3ZrYTlmc3daaFc0QmdjCmNTNnk1bGRNOGFUSi9YcjREMnNx
        VitoNTVpV3lhZFcyOVBQTWNoM2VaakEKLS0tIDkySlZQRGREcFhxeGcreW81endh
        TUpWQkhLZzJBSXdJM0JDVndmRnFrdFkKY1I+9vj1kkAnr9ytMimJwUcuDtmEvgk/
        lDS8eEP/7qIFGo0hSelAuLSiF107owFzAoSy2aFBCBwh/Pl2EEd5Ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T10:05:06Z"
  mac: ENC[AES256_GCM,data:Ju4P34tRLHJ/Bj2G755ZjZmPO13mCR6dWtTNLEjaF4p7JsJjO080hzZLQDHlQmLJIOJ5LeEvw+SjDjVPC6YewoLA/HVXwwwliMjI+4Rd8PrJdlcX55jbnabaxrUq7uiJAgcidj3T823YoAs72Roe7tPg3mr9lftG8ctzftMbGwE=,iv:PmDRnFceMtDkjOiXpCkJJMKXKqx//S0jhHLoB0iDVt8=,tag:j2GRiqSEriogdGn0npIS6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
