apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UGutYz9ceu/664A1TgWpsnQPXj6FbcQAUYmTyFUZps3RKro=,iv:UQCbt/QLBzeS4RlWwNC4RrV0sr6LpMijwwTb4Sd1taQ=,tag:SqpvVHi6Ob1hoNPIWofXrQ==,type:comment]
    #ENC[AES256_GCM,data:XEEeaHdIEQsIIhvwCu+IPrNsFYUDvEE6ifjzTK7mm9Xf1Gx0UuRYaqoL6V5MW2bNge+sb+746dQcNaBqS7w=,iv:NPQV1AXXWXrnUyUIGGCkgGsnGD/Tay9uZenRiaQgWt4=,tag:vWwto2Tz2OSz/JwvH5EyUg==,type:comment]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:+nWKGgqUNTg19hfOaOttXfce9pVihiYb6ETiZ+dQ1N6s4LZy2uaPGg==,iv:zi3cOGYcy7oCLWnGa6FIEiEb2UU1QiYiXxhTD4/WApw=,tag:/rkiNWblB2P7PYvfJm1y4w==,type:str]
    #ENC[AES256_GCM,data:w5RtnLeytKlb6dA6aCKDrt6XPHKBa3766tPbILXACaZKROo=,iv:FPyZUXlpNXBaU8cB1Aaopi4uoobLh5FvZ6IjOKAMTNU=,tag:T0YivfZoT/ZNoKmSzSn7bA==,type:comment]
    RENOVATE_REPOSITORIES: ENC[AES256_GCM,data:8udRZ15JdCAUczVv66VwAtzfzti85Q==,iv:1KYYTzI8oDg218yB826j/OOANYqByyFRJcnN8CFjSV0=,tag:yOXpQUsYHgTlw0so3Wdq1w==,type:str]
    #ENC[AES256_GCM,data:2ofy/4jqpvAv7j7Lw1tH1Lky0igxsJw=,iv:iW1z2oP9CuXGMJsxcZI0jF/V1qDl7P8Dq823Z6058ms=,tag:GyyEybfUFIBaUtOzCtt7Kw==,type:comment]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:KYX7m48Q79flLoMqJHqMwa0yoS6lkTYGuhPsKauVQreB3w==,iv:0tCHsqfkZruSPnzczk2RDJ9iDxs2papEINLqVE/COYc=,tag:7DYAVVhTWrouPZaFm3JMIg==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSVlpTU1PejIyTmtYbFQz
            NGJ2cmVodnpVWU9ZVDNFelM4SGFZN1dod0dnCmdyZTlRcFJaa1ZTWGRUYVFkZW9q
            UzZrZ2ZRMU1FaVFyczVEY2Y0L1BvYWsKLS0tIE5pbXJpcmFyTVlhaDBMTGVwSTlm
            NnlWbjhFRXBqc21ZWVVjVGxRcDRGRG8Kshxt5Org13v/3XRihgn0jStIvWo4NBYS
            4/rIdaALNZFiO8sb2CVuOCdPMV1z9tn1WSV5YDNKbaNYjflrqgTa9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T16:30:50Z"
    mac: ENC[AES256_GCM,data:vcMsa53PSSuQept3hDkH0vePp35p7gELLBUoBGKnw/tE2feCpmXtYDOAAGKCG1Az910y1exXtYNb9IC88vXGj2n2zZfZXb60lVOG40S8uP3MFPNm0oXFkdTk8wBSQch2PLhG8GFQOhq0xFAQ/5EyBSwYTUXj+nkRMpnzRFbyfPw=,iv:P0zQGCP98CyYIoxRiW5ia5XSIuaGytLMH0VMvGzmj1o=,tag:noADaUxlXXdQWGNZ0sJVew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
