apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:e9c424bk/fUi1wLG5nuty0UV0U53tiSyEZKkW3aCm4lEwXI=,iv:SeovuySVe32QSE4qns2zVuBR5/LIThQ5/5ZNsgYaZvQ=,tag:8ZRTZ7Z1lN4Nfwx/TnvEzw==,type:comment]
    #ENC[AES256_GCM,data:w8BvyJwSMgaM5ObFoZWBD2N7sX9P3it9XNBoBatKCVwN933CcAARnRaB/IQP4EZ/Ov2CwLg9ag2YgWuCn84=,iv:Qxhvksnc2JxlCtljmkW/SozZ4mUBTXx/0G6aHGahVe8=,tag:syzSwq8TE4WUSpceUFhnjg==,type:comment]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:cp6AEMC2fQTpz7j3aNptkHLDTBGR4V4nauFA39SE8mmSvRUdULLeUw==,iv:c8PlkWNR5G3Afa9kvMG38Eo/ty0CEPduDsAsic1sRzQ=,tag:0cEBJ8jcdYWxRyjU95s8Pg==,type:str]
    #ENC[AES256_GCM,data:oe1Y9SvzkmCHn8GEEb74UG84Ehp0Bx572QOXtQlBell0/qI=,iv:Pbb30dqtDjmqD91/4IKyWhKrSUdGFcaK0yq41dokTZo=,tag:/gWXwIwBgOavTn0uME9otg==,type:comment]
    RENOVATE_REPOSITORIES: ENC[AES256_GCM,data:Y6a2xJ7LuzYVerLIhKTUITyj+qdAfA==,iv:jS56yqVhQWCzbTNPhnqs6RJ1eCcdJifU0wUNWOuMJlM=,tag:3wFduEwPD1G3VMbWPBGarQ==,type:str]
    #ENC[AES256_GCM,data:m1RMY8DNi+WFHvhPK30d/yDoPTVt4xE=,iv:c/jVbH527QrZ7yvamRDCSy+SuEG6z9jex5fy+gQM728=,tag:Hpfnhpp8XVkQDGpBLlvQpA==,type:comment]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:S0i1pyVxSVI5E5MLkeyTvdMc4GLO7GY9Bn9iFXXiLDZfVA==,iv:ZIaBtX+jo4ZcY8jeBT7DdeBY0qBhutrYPgtIHOb2tDM=,tag:fNk1VxFjhWZxfz3XQr0KoA==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0VxdTVVUncvL3hwMm5J
            T2p4N2tpYmM0N3l5VGZHdEt1U0FIbllhb2dNCmpDTDJoZ0oxaVBxWXNCYUZxR21R
            N0hYUUVNejhmRWNzMmcyelRIVlFodVEKLS0tIDQvS1J0WndpWE9oaTZMMEd6RjlF
            OENZazRKbjk3YzUrZnkzRmV3Tm0wT3cKI/T7rnT3o//FXiKyJiHOIPozdSkyfBm8
            noJFACaU3XXqPC8ZpjtUZcylTM34yjWDIcGOhIq0FI9NOPej4Oa0XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T10:12:03Z"
    mac: ENC[AES256_GCM,data:qwAlV035SNi3d7LBzHbjFRfhFn0HN6d1eKEuv/mdvQfjLvhKr0Ca4EXcTuGiCDZ1KNaDtCW4ZJFega4sa9NXUC4YwwWXXjHr0A6AgVrHRutDre+QQUFGMS4l99adKBU/16KzOeyZsPcr3Z0hTRFV61JjVJsMP75MRgW/Gr30Uug=,iv:EX5VH5z2E+PJk42pH81zvAEHGSp/VVeT2sP+pZfQ1F4=,tag:Mwd+TL1C4Ksz2LZ36seNUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
