# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.5.0/charts/other/app-template/values.schema.json

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      open-webui:
        type: deployment
        replicas: 1
        strategy: Recreate

        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.40
            env:
              - name: OLLAMA_BASE_URL
                value: "http://ollama:11434"
              - name: WEBUI_AUTH
                value: "true"
    service:
      app:
        controller: open-webui
        ports:
          http:
            port: 8080
            protocol: TCP

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: ai.erwanleboucher.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: ai-tls
            hosts:
              - ai.erwanleboucher.dev



